//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAppCoordConversionModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProAppCoordConversionModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name.
        /// </summary>
        public static string AdditionalFieldName {
            get {
                return ResourceManager.GetString("AdditionalFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Value.
        /// </summary>
        public static string AdditionalFieldValue {
            get {
                return ResourceManager.GetString("AdditionalFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Layer.
        /// </summary>
        public static string AddLayerCap {
            get {
                return ResourceManager.GetString("AddLayerCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a basemap or a layer to the map..
        /// </summary>
        public static string AddLayerMsg {
            get {
                return ResourceManager.GetString("AddLayerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat / Lon.
        /// </summary>
        public static string AmbiguousLatLon {
            get {
                return ResourceManager.GetString("AmbiguousLatLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lon / Lat.
        /// </summary>
        public static string AmbiguousLonLat {
            get {
                return ResourceManager.GetString("AmbiguousLonLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show me this message again.
        /// </summary>
        public static string AmbiguousMsg {
            get {
                return ResourceManager.GetString("AmbiguousMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous Coordinates.
        /// </summary>
        public static string AmbiguousTitle {
            get {
                return ResourceManager.GetString("AmbiguousTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous coordinates have been entered.  Please choose from the following:.
        /// </summary>
        public static string AmbiguoustxtCoords {
            get {
                return ResourceManager.GetString("AmbiguoustxtCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Feature Class.
        /// </summary>
        public static string CaptionOverwrite {
            get {
                return ResourceManager.GetString("CaptionOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string CategoryListDD {
            get {
                return ResourceManager.GetString("CategoryListDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM.
        /// </summary>
        public static string CategoryListDDM {
            get {
                return ResourceManager.GetString("CategoryListDDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        public static string CategoryListDMS {
            get {
                return ResourceManager.GetString("CategoryListDMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GARS.
        /// </summary>
        public static string CategoryListGARS {
            get {
                return ResourceManager.GetString("CategoryListGARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS.
        /// </summary>
        public static string CategoryListMGRS {
            get {
                return ResourceManager.GetString("CategoryListMGRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USNG.
        /// </summary>
        public static string CategoryListUSNG {
            get {
                return ResourceManager.GetString("CategoryListUSNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string CategoryListUTM {
            get {
                return ResourceManager.GetString("CategoryListUTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoordinateDD.ToString(): Invalid formatting string..
        /// </summary>
        public static string CoordDDExcept {
            get {
                return ResourceManager.GetString("CoordDDExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoordinateDDM.ToString(): Invalid formatting string..
        /// </summary>
        public static string CoordDDMExcept {
            get {
                return ResourceManager.GetString("CoordDDMExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoordinateDMS.ToString(): Invalid formatting string..
        /// </summary>
        public static string CoordDMSExcept {
            get {
                return ResourceManager.GetString("CoordDMSExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must override CoordinateFormatterBase.Format!.
        /// </summary>
        public static string CoordFBaseExcept {
            get {
                return ResourceManager.GetString("CoordFBaseExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoordinateGARS.ToString(): Invalid formatting string..
        /// </summary>
        public static string CoordGARSExcept {
            get {
                return ResourceManager.GetString("CoordGARSExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoordinateMGRS.ToString(): Invalid formatting string..
        /// </summary>
        public static string CoordMGRSExcept {
            get {
                return ResourceManager.GetString("CoordMGRSExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a basemap or layer to the map..
        /// </summary>
        public static string CoordsOutOfBoundsAddlMsg {
            get {
                return ResourceManager.GetString("CoordsOutOfBoundsAddlMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates out of Bounds.
        /// </summary>
        public static string CoordsoutOfBoundsCaption {
            get {
                return ResourceManager.GetString("CoordsoutOfBoundsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates or measures are out of bounds..
        /// </summary>
        public static string CoordsOutOfBoundsMsg {
            get {
                return ResourceManager.GetString("CoordsOutOfBoundsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Coordinate System.
        /// </summary>
        public static string CoordSysDialogTitle {
            get {
                return ResourceManager.GetString("CoordSysDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current coordinate system:.
        /// </summary>
        public static string CoordSysPickerHeader {
            get {
                return ResourceManager.GetString("CoordSysPickerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string CoordSysPickerName {
            get {
                return ResourceManager.GetString("CoordSysPickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKID:.
        /// </summary>
        public static string CoordSysPickerWKID {
            get {
                return ResourceManager.GetString("CoordSysPickerWKID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKT:.
        /// </summary>
        public static string CoordSysPickerWKT {
            get {
                return ResourceManager.GetString("CoordSysPickerWKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoordinateUTM.ToString(): Invalid formatting string..
        /// </summary>
        public static string CoordUTMExcept {
            get {
                return ResourceManager.GetString("CoordUTMExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Successful.
        /// </summary>
        public static string CSVExportSuccessfulCaption {
            get {
                return ResourceManager.GetString("CSVExportSuccessfulCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to .
        /// </summary>
        public static string CSVExportSuccessfulMessage {
            get {
                return ResourceManager.GetString("CSVExportSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose location to create CSV file.
        /// </summary>
        public static string CSVLocationMessage {
            get {
                return ResourceManager.GetString("CSVLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomString {
            get {
                return ResourceManager.GetString("CustomString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error .
        /// </summary>
        public static string DebugWriteError {
            get {
                return ResourceManager.GetString("DebugWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert coordinate: .
        /// </summary>
        public static string DebugWriteFailed {
            get {
                return ResourceManager.GetString("DebugWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to header :.
        /// </summary>
        public static string DebugWriteHeader {
            get {
                return ResourceManager.GetString("DebugWriteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string DialogData {
            get {
                return ResourceManager.GetString("DialogData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        public static string DialogError {
            get {
                return ResourceManager.GetString("DialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point is out of bounds.
        /// </summary>
        public static string DialogPointBoundMsg {
            get {
                return ResourceManager.GetString("DialogPointBoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point is out of bounds.
        /// </summary>
        public static string DialogPointBoundTitle {
            get {
                return ResourceManager.GetString("DialogPointBoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Spatial Reference.
        /// </summary>
        public static string EditOuputConfigure {
            get {
                return ResourceManager.GetString("EditOuputConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Reference.
        /// </summary>
        public static string EditOutputHeader {
            get {
                return ResourceManager.GetString("EditOutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Color.
        /// </summary>
        public static string EditPropColor {
            get {
                return ResourceManager.GetString("EditPropColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Symbol.
        /// </summary>
        public static string EditPropCSym {
            get {
                return ResourceManager.GetString("EditPropCSym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Ambiguous Coordinates Dialog.
        /// </summary>
        public static string EditPropDisplay {
            get {
                return ResourceManager.GetString("EditPropDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string EditPropLoad {
            get {
                return ResourceManager.GetString("EditPropLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbology.
        /// </summary>
        public static string EditPropSym {
            get {
                return ResourceManager.GetString("EditPropSym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string EnumCTDD {
            get {
                return ResourceManager.GetString("EnumCTDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM.
        /// </summary>
        public static string EnumCTDDM {
            get {
                return ResourceManager.GetString("EnumCTDDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        public static string EnumCTDMS {
            get {
                return ResourceManager.GetString("EnumCTDMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GARS.
        /// </summary>
        public static string EnumCTGARS {
            get {
                return ResourceManager.GetString("EnumCTGARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS.
        /// </summary>
        public static string EnumCTMGRS {
            get {
                return ResourceManager.GetString("EnumCTMGRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Map Unit.
        /// </summary>
        public static string EnumCTNone {
            get {
                return ResourceManager.GetString("EnumCTNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USNG.
        /// </summary>
        public static string EnumCTUSNG {
            get {
                return ResourceManager.GetString("EnumCTUSNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string EnumCTUTM {
            get {
                return ResourceManager.GetString("EnumCTUTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Field.
        /// </summary>
        public static string EnumSITDF {
            get {
                return ResourceManager.GetString("EnumSITDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Field.
        /// </summary>
        public static string EnumSITSF {
            get {
                return ResourceManager.GetString("EnumSITSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnImportCSVFileCommand Error .
        /// </summary>
        public static string FailedImportCsv {
            get {
                return ResourceManager.GetString("FailedImportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed in OnImportCoordinates:.
        /// </summary>
        public static string FailedWriteLine {
            get {
                return ResourceManager.GetString("FailedWriteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string FCLUtilsCFError {
            get {
                return ResourceManager.GetString("FCLUtilsCFError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcelToTable_conversion operation failed..
        /// </summary>
        public static string FCLUtilsIFEError {
            get {
                return ResourceManager.GetString("FCLUtilsIFEError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv files|*.csv|Excel 97-2003 Workbook (*.xls)|*.xls|Excel Workbook (*.xlsx)|*.xlsx.
        /// </summary>
        public static string FileDialogFilterAll {
            get {
                return ResourceManager.GetString("FileDialogFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv files|*.csv.
        /// </summary>
        public static string FileDialogFiltercsv {
            get {
                return ResourceManager.GetString("FileDialogFiltercsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string FileDialogTitle {
            get {
                return ResourceManager.GetString("FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Exported to .
        /// </summary>
        public static string FileExport {
            get {
                return ResourceManager.GetString("FileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}?.
        /// </summary>
        public static string FormattedRemove {
            get {
                return ResourceManager.GetString("FormattedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string HeaderAdvanced {
            get {
                return ResourceManager.GetString("HeaderAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect.
        /// </summary>
        public static string HeaderCollect {
            get {
                return ResourceManager.GetString("HeaderCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string HeaderConvert {
            get {
                return ResourceManager.GetString("HeaderConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate.
        /// </summary>
        public static string HeaderCoordinate {
            get {
                return ResourceManager.GetString("HeaderCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string HeaderFlash {
            get {
                return ResourceManager.GetString("HeaderFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string HeaderInput {
            get {
                return ResourceManager.GetString("HeaderInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string HeaderList {
            get {
                return ResourceManager.GetString("HeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string HeaderOutput {
            get {
                return ResourceManager.GetString("HeaderOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Field information associated with this point.
        /// </summary>
        public static string InformationNotAvailableMsg {
            get {
                return ResourceManager.GetString("InformationNotAvailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Coordinate.
        /// </summary>
        public static string InvalidCoordCap {
            get {
                return ResourceManager.GetString("InvalidCoordCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid coordinate.
        /// </summary>
        public static string InvalidCoordMsg {
            get {
                return ResourceManager.GetString("InvalidCoordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose location to create KMZ file.
        /// </summary>
        public static string KMLLocationMessage {
            get {
                return ResourceManager.GetString("KMLLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LabelCategory {
            get {
                return ResourceManager.GetString("LabelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string LabelClearAll {
            get {
                return ResourceManager.GetString("LabelClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Coordinates.
        /// </summary>
        public static string LabelClearAllCap {
            get {
                return ResourceManager.GetString("LabelClearAllCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Graphics.
        /// </summary>
        public static string LabelClearGraphics {
            get {
                return ResourceManager.GetString("LabelClearGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Removal?.
        /// </summary>
        public static string LabelConfirmRemoval {
            get {
                return ResourceManager.GetString("LabelConfirmRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Coordinate.
        /// </summary>
        public static string LabelDisplayCoordinate {
            get {
                return ResourceManager.GetString("LabelDisplayCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string LabelExport {
            get {
                return ResourceManager.GetString("LabelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Coordinates.
        /// </summary>
        public static string LabelExportCap {
            get {
                return ResourceManager.GetString("LabelExportCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Field (Longitude).
        /// </summary>
        public static string LabelField1 {
            get {
                return ResourceManager.GetString("LabelField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Field (Latitude).
        /// </summary>
        public static string LabelField2 {
            get {
                return ResourceManager.GetString("LabelField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X/Y.
        /// </summary>
        public static string LabelFieldCombined {
            get {
                return ResourceManager.GetString("LabelFieldCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        public static string LabelFormats {
            get {
                return ResourceManager.GetString("LabelFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string LabelImport {
            get {
                return ResourceManager.GetString("LabelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Coordinates.
        /// </summary>
        public static string LabelImportCap {
            get {
                return ResourceManager.GetString("LabelImportCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Type.
        /// </summary>
        public static string LabelInputType {
            get {
                return ResourceManager.GetString("LabelInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string LabelSample {
            get {
                return ResourceManager.GetString("LabelSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string LabelSaveAs {
            get {
                return ResourceManager.GetString("LabelSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show N/S/E/W for hemisphere.
        /// </summary>
        public static string LabelShowHemisphere {
            get {
                return ResourceManager.GetString("LabelShowHemisphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show - for S/W hemisphere.
        /// </summary>
        public static string LabelShowHyphen {
            get {
                return ResourceManager.GetString("LabelShowHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show + for N/E hemisphere.
        /// </summary>
        public static string LabelShowPlus {
            get {
                return ResourceManager.GetString("LabelShowPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while map loads....
        /// </summary>
        public static string LoadMapMsg {
            get {
                return ResourceManager.GetString("LoadMapMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MenuLabelCopy {
            get {
                return ResourceManager.GetString("MenuLabelCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All.
        /// </summary>
        public static string MenuLabelCopyAll {
            get {
                return ResourceManager.GetString("MenuLabelCopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuLabelDelete {
            get {
                return ResourceManager.GetString("MenuLabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string MenuLabelDeleteAll {
            get {
                return ResourceManager.GetString("MenuLabelDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string MsgErrorName {
            get {
                return ResourceManager.GetString("MsgErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already used..
        /// </summary>
        public static string Msgis {
            get {
                return ResourceManager.GetString("Msgis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be 10 characters or less..
        /// </summary>
        public static string MsgLess {
            get {
                return ResourceManager.GetString("MsgLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found..
        /// </summary>
        public static string MsgNoDataFound {
            get {
                return ResourceManager.GetString("MsgNoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name should not start with a number..
        /// </summary>
        public static string MsgNumber {
            get {
                return ResourceManager.GetString("MsgNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name should only contain alphabet and numbers..
        /// </summary>
        public static string MsgOthers {
            get {
                return ResourceManager.GetString("MsgOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve selected a feature class that already exists. Do you wish to replace it?.
        /// </summary>
        public static string MsgOverwrite {
            get {
                return ResourceManager.GetString("MsgOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name.
        /// </summary>
        public static string MsgThe {
            get {
                return ResourceManager.GetString("MsgThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string OutputConfigure {
            get {
                return ResourceManager.GetString("OutputConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string OutputDelete {
            get {
                return ResourceManager.GetString("OutputDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop-up.
        /// </summary>
        public static string Popup {
            get {
                return ResourceManager.GetString("Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.. Please wait.
        /// </summary>
        public static string ProgressDlg {
            get {
                return ResourceManager.GetString("ProgressDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string SaveAsCSV {
            get {
                return ResourceManager.GetString("SaveAsCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature class.
        /// </summary>
        public static string SaveAsFCL {
            get {
                return ResourceManager.GetString("SaveAsFCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMZ.
        /// </summary>
        public static string SaveAsKMZ {
            get {
                return ResourceManager.GetString("SaveAsKMZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapefile.
        /// </summary>
        public static string SaveAsShape {
            get {
                return ResourceManager.GetString("SaveAsShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output.
        /// </summary>
        public static string SaveAsTitle {
            get {
                return ResourceManager.GetString("SaveAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show N/S/E/W.
        /// </summary>
        public static string ShowNSEW {
            get {
                return ResourceManager.GetString("ShowNSEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show +/-.
        /// </summary>
        public static string ShowPlusHyphen {
            get {
                return ResourceManager.GetString("ShowPlusHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters &apos;+&apos;,&apos;-&apos;,&apos;N&apos;,&apos;W&apos;,&apos;E&apos; and &apos;S&apos; are not allowed to define custom formatting..
        /// </summary>
        public static string SpecialCharactersValidationMsg {
            get {
                return ResourceManager.GetString("SpecialCharactersValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easting.
        /// </summary>
        public static string StringEasting {
            get {
                return ResourceManager.GetString("StringEasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Sq.
        /// </summary>
        public static string StringGridSq {
            get {
                return ResourceManager.GetString("StringGridSq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GZD.
        /// </summary>
        public static string StringGZD {
            get {
                return ResourceManager.GetString("StringGZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string StringKey {
            get {
                return ResourceManager.GetString("StringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string StringLat {
            get {
                return ResourceManager.GetString("StringLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lon.
        /// </summary>
        public static string StringLon {
            get {
                return ResourceManager.GetString("StringLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Format Found.
        /// </summary>
        public static string StringNoFormatFound {
            get {
                return ResourceManager.GetString("StringNoFormatFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northing.
        /// </summary>
        public static string StringNorthing {
            get {
                return ResourceManager.GetString("StringNorthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrant.
        /// </summary>
        public static string StringQuadrant {
            get {
                return ResourceManager.GetString("StringQuadrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string StringZone {
            get {
                return ResourceManager.GetString("StringZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Output Coordinate.
        /// </summary>
        public static string TitleAddNewOutputCoordinate {
            get {
                return ResourceManager.GetString("TitleAddNewOutputCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Output Coordinate.
        /// </summary>
        public static string TitleEditOutputCoordinate {
            get {
                return ResourceManager.GetString("TitleEditOutputCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Properties.
        /// </summary>
        public static string TitleEditProperties {
            get {
                return ResourceManager.GetString("TitleEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Fields.
        /// </summary>
        public static string TitleSelectCoordinateFields {
            get {
                return ResourceManager.GetString("TitleSelectCoordinateFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output.
        /// </summary>
        public static string TitleSelectOutput {
            get {
                return ResourceManager.GetString("TitleSelectOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TooltipAdd {
            get {
                return ResourceManager.GetString("TooltipAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Point.
        /// </summary>
        public static string ToolTipCoordPoint {
            get {
                return ResourceManager.GetString("ToolTipCoordPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string TooltipCopy {
            get {
                return ResourceManager.GetString("TooltipCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All.
        /// </summary>
        public static string TooltipCopyAll {
            get {
                return ResourceManager.GetString("TooltipCopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Properties.
        /// </summary>
        public static string TooltipEditProperties {
            get {
                return ResourceManager.GetString("TooltipEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Point Tool.
        /// </summary>
        public static string TooltipMapPointTool {
            get {
                return ResourceManager.GetString("TooltipMapPointTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportCSV.GetSeparator(): Unrecognized field delimter..
        /// </summary>
        public static string UnrecognizedDelimiter {
            get {
                return ResourceManager.GetString("UnrecognizedDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use two fields.
        /// </summary>
        public static string UseTwoFields {
            get {
                return ResourceManager.GetString("UseTwoFields", resourceCulture);
            }
        }
    }
}
