//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoordinateConversionLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoordinateConversionLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string CategoryListDD {
            get {
                return ResourceManager.GetString("CategoryListDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM.
        /// </summary>
        public static string CategoryListDDM {
            get {
                return ResourceManager.GetString("CategoryListDDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        public static string CategoryListDMS {
            get {
                return ResourceManager.GetString("CategoryListDMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GARS.
        /// </summary>
        public static string CategoryListGARS {
            get {
                return ResourceManager.GetString("CategoryListGARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS.
        /// </summary>
        public static string CategoryListMGRS {
            get {
                return ResourceManager.GetString("CategoryListMGRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USNG.
        /// </summary>
        public static string CategoryListUSNG {
            get {
                return ResourceManager.GetString("CategoryListUSNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string CategoryListUTM {
            get {
                return ResourceManager.GetString("CategoryListUTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomString {
            get {
                return ResourceManager.GetString("CustomString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string EnumCTDD {
            get {
                return ResourceManager.GetString("EnumCTDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM.
        /// </summary>
        public static string EnumCTDDM {
            get {
                return ResourceManager.GetString("EnumCTDDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        public static string EnumCTDMS {
            get {
                return ResourceManager.GetString("EnumCTDMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GARS.
        /// </summary>
        public static string EnumCTGARS {
            get {
                return ResourceManager.GetString("EnumCTGARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS.
        /// </summary>
        public static string EnumCTMGRS {
            get {
                return ResourceManager.GetString("EnumCTMGRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Map Unit.
        /// </summary>
        public static string EnumCTNone {
            get {
                return ResourceManager.GetString("EnumCTNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USNG.
        /// </summary>
        public static string EnumCTUSNG {
            get {
                return ResourceManager.GetString("EnumCTUSNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string EnumCTUTM {
            get {
                return ResourceManager.GetString("EnumCTUTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}?.
        /// </summary>
        public static string FormattedRemove {
            get {
                return ResourceManager.GetString("FormattedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string HeaderAdvanced {
            get {
                return ResourceManager.GetString("HeaderAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate.
        /// </summary>
        public static string HeaderCoordinate {
            get {
                return ResourceManager.GetString("HeaderCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LabelCategory {
            get {
                return ResourceManager.GetString("LabelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Removal?.
        /// </summary>
        public static string LabelConfirmRemoval {
            get {
                return ResourceManager.GetString("LabelConfirmRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Coordinate.
        /// </summary>
        public static string LabelDisplayCoordinate {
            get {
                return ResourceManager.GetString("LabelDisplayCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        public static string LabelFormats {
            get {
                return ResourceManager.GetString("LabelFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string LabelSample {
            get {
                return ResourceManager.GetString("LabelSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easting.
        /// </summary>
        public static string StringEasting {
            get {
                return ResourceManager.GetString("StringEasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Sq.
        /// </summary>
        public static string StringGridSq {
            get {
                return ResourceManager.GetString("StringGridSq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GZD.
        /// </summary>
        public static string StringGZD {
            get {
                return ResourceManager.GetString("StringGZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string StringKey {
            get {
                return ResourceManager.GetString("StringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string StringLat {
            get {
                return ResourceManager.GetString("StringLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lon.
        /// </summary>
        public static string StringLon {
            get {
                return ResourceManager.GetString("StringLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Format Found.
        /// </summary>
        public static string StringNoFormatFound {
            get {
                return ResourceManager.GetString("StringNoFormatFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northing.
        /// </summary>
        public static string StringNorthing {
            get {
                return ResourceManager.GetString("StringNorthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrant.
        /// </summary>
        public static string StringQuadrant {
            get {
                return ResourceManager.GetString("StringQuadrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string StringZone {
            get {
                return ResourceManager.GetString("StringZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Output Coordinate.
        /// </summary>
        public static string TitleAddNewOutputCoordinate {
            get {
                return ResourceManager.GetString("TitleAddNewOutputCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Output Coordinate.
        /// </summary>
        public static string TitleEditOutputCoordinate {
            get {
                return ResourceManager.GetString("TitleEditOutputCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Properties.
        /// </summary>
        public static string TitleEditProperties {
            get {
                return ResourceManager.GetString("TitleEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TooltipAdd {
            get {
                return ResourceManager.GetString("TooltipAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string TooltipCopy {
            get {
                return ResourceManager.GetString("TooltipCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All.
        /// </summary>
        public static string TooltipCopyAll {
            get {
                return ResourceManager.GetString("TooltipCopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Properties.
        /// </summary>
        public static string TooltipEditProperties {
            get {
                return ResourceManager.GetString("TooltipEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Point Tool.
        /// </summary>
        public static string TooltipMapPointTool {
            get {
                return ResourceManager.GetString("TooltipMapPointTool", resourceCulture);
            }
        }
    }
}
